
# Maze

name: Test

on:
  push

jobs:
        
  java:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: |
        sudo cpan -T -i Data::Table::Text Digest::SHA1 Date::Manip DBI DBD::Pg    
    - name: Test
      run: |
        javac -d . -g Maze.java 
        java -ea -cp . Test.Maze 2> output.txt
        cat output.txt
        ls -la
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} perl upload.pl 
